ASPCORE-CRUD/Models/AddEmployeeViewModel.cs
namespace ASPCORE_CRUD.Models
{
    public class AddEmployeeViewModel
    {
        public string? Name { get; set; }
        public string? Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string? Department { get; set; }
    }
}

ASPCORE-CRUD/Models/Domain/Employee.cs
namespace ASPCORE_CRUD.Models.Domain
{
    public class Employee
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string? Department { get; set; }
    }
}

ASPCORE-CRUD/Models/ErrorViewModel.cs
namespace ASPCORE_CRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPCORE-CRUD/Models/UpdateEmployeeViewModel.cs
namespace ASPCORE_CRUD.Models
{
    public class UpdateEmployeeViewModel
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string? Department { get; set; }
    }
}

ASPCORE-CRUD/Controllers/EmployeesController.cs
using ASPCORE_CRUD.Data;
using ASPCORE_CRUD.Models;
using ASPCORE_CRUD.Models.Domain;
using Azure.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPCORE_CRUD.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly EmployeeDbContext context;

        public EmployeesController(EmployeeDbContext _context)
        {
            context = _context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var empDb = await context.Employees.ToListAsync();

            

            return View(empDb);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEmployeeViewModel request)
        {
            var employee = new Employee() 
            {
                Id = Guid.NewGuid(),
                Name = request.Name,
                Email = request.Email,
                DateOfBirth = request.DateOfBirth,
                Department = request.Department,
                Salary = request.Salary
            };

            await context.Employees.AddAsync(employee);

            await context.SaveChangesAsync();

            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var employee = await context.Employees.FirstOrDefaultAsync(e => e.Id == id);
            var viewModel = new UpdateEmployeeViewModel();

            if(employee != null)
            {
                viewModel = new UpdateEmployeeViewModel()
                {
                    Id = Guid.NewGuid(),
                    Name = employee.Name,
                    Email = employee.Email,
                    DateOfBirth = employee.DateOfBirth,
                    Department = employee.Department,
                    Salary = employee.Salary
                };

                return await Task.Run(() => View("View", viewModel));
            }
            else
            {
                return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateEmployeeViewModel viewModel)
        {
            var emp = await context.Employees.FindAsync(viewModel.Id);

            if(emp != null)
            {
                emp.Name = viewModel.Name;
                emp.Email = viewModel.Email;
                emp.Salary = viewModel.Salary;
                emp.DateOfBirth = viewModel.DateOfBirth;
                emp.Department = viewModel.Department;

                await context.SaveChangesAsync(); 

            }

            return RedirectToAction("Index");
        }
    }
}

ASPCORE-CRUD/Controllers/HomeController.cs
using ASPCORE_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPCORE_CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPCORE-CRUD/Views/Employees/Add.cshtml
@model ASPCORE_CRUD.Models.AddEmployeeViewModel

<h1>Add Employee</h1>
<form method="post" action="Add" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name"/>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email" />
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="Salary" />
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Date of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth"/>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department"/>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

ASPCORE-CRUD/Views/Employees/Index.cshtml
@using ASPCORE_CRUD.Models.Domain;
@model List<Employee>

<h1>Employees</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Salary</th>
            <th>Date of Birth</th>
            <th>Salary</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.Id</td>
                <td>@employee.Name</td>
                <td>@employee.Email</td>
                <td>@employee.Salary</td>
                <td>@employee.DateOfBirth.ToString("dd-MM-yyyy")</td>
                <td>@employee.Department</td>
                <td>
                    <a class="btn btn-primary mr-2" href="employees/view/@employee.Id">View</a>   
                </td>
            </tr>
        }
    </tbody>
</table>

ASPCORE-CRUD/Views/Employees/View.cshtml
@model ASPCORE_CRUD.Models.UpdateEmployeeViewModel


<h1>Edit Employee</h1>
<form method="post" action="View" class="mt-5">
    <div class="mb-3">
        <label for="" class="form-label">ID</label>
        <input type="text" class="form-control" asp-for="Id" readonly/>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Name</label>
        <input type="text" class="form-control" asp-for="Name"/>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Email Address</label>
        <input type="email" class="form-control" asp-for="Email" />
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Salary</label>
        <input type="number" class="form-control" asp-for="Salary" />
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Date of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth"/>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Department</label>
        <input type="text" class="form-control" asp-for="Department"/>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

ASPCORE-CRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPCORE-CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPCORE_CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPCORE_CRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPCORE_CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Add">Add Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ASPCORE_CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>